module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  book: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  ckeditor_div_manager: 0
  color: 0
  colorbox: 0
  colorbox_inline: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  htmlpurifier: 0
  image: 0
  insert: 0
  language: 0
  libraries: 0
  link: 0
  media: 0
  menu_breadcrumb: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  raven: 0
  rdf: 0
  recaptcha: 0
  search: 0
  shortcut: 0
  simple_block: 0
  superfish: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  dpm_classy: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
